Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"
  config.vm.provision "shell", path: "provision.sh"
  #config.vm.network "private_network", type: "dhcp"
  config.vm.network "public_network", bridge: [
    "en0",
    "en7",
    "en12",
    "en15",
  ]
  config.vm.provider "vmware_desktop" do |v|
    v.memory = "1024"
    v.cpus = 2
  end
end

